
import { MenuItem } from './types';

export const MENU_DATA: MenuItem[] = [
    // Традиционные грузинские
    { id: 1, category: "Традиционные", name: "Чашушули", oldPrice: 600, newPrice: 650 },
    { id: 2, category: "Традиционные", name: "Шкмерули", oldPrice: 700, newPrice: 750 },
    { id: 3, category: "Традиционные", name: "Оджахури", oldPrice: 700, newPrice: 750 },
    { id: 4, category: "Традиционные", name: "Кучмачи", oldPrice: 500, newPrice: 550 },
    { id: 5, category: "Традиционные", name: "Лобио Котанши", oldPrice: 400, newPrice: 450 },
    { id: 6, category: "Традиционные", name: "Люля Кебаб", oldPrice: 600, newPrice: 650 },
    { id: 7, category: "Традиционные", name: "Чахохбили", oldPrice: 550, newPrice: 600 },
    { id: 8, category: "Традиционные", name: "Цисарткела", oldPrice: 600, newPrice: 650 },
    { id: 9, category: "Традиционные", name: "Долма", oldPrice: 500, newPrice: 550 },
    { id: 10, category: "Традиционные", name: "Грибы с сыром", oldPrice: 550, newPrice: 600 },
    { id: 11, category: "Традиционные", name: "Куриный стейк", oldPrice: 750, newPrice: 800 },
    { id: 12, category: "Традиционные", name: "Курица по-арабски", oldPrice: 600, newPrice: 650 },
    { id: 13, category: "Традиционные", name: "Грузия", oldPrice: 700, newPrice: 750 },
    { id: 14, category: "Традиционные", name: "Цыпленок табака", oldPrice: 800, newPrice: 850 },
    { id: 15, category: "Традиционные", name: "Курица по-фламандски", oldPrice: 600, newPrice: 650 },
    { id: 16, category: "Традиционные", name: "Жульен", oldPrice: 500, newPrice: 550 },
    { id: 17, category: "Традиционные", name: "Форель по-домашнему", oldPrice: 1200, newPrice: 1250 },
    { id: 18, category: "Традиционные", name: "Стейк сёмги", oldPrice: 1400, newPrice: 1450 },
    { id: 19, category: "Традиционные", name: "Апхазура", oldPrice: 700, newPrice: 750 },
    { id: 20, category: "Традиционные", name: "Жареный сулугуни", oldPrice: 550, newPrice: 600 },
    // Салаты
    { id: 21, category: "Салаты", name: "Греческий", oldPrice: 400, newPrice: 450 },
    { id: 22, category: "Салаты", name: "Итальянский", oldPrice: 550, newPrice: 600 },
    { id: 23, category: "Салаты", name: "Салат с рукколой и курицей", oldPrice: 500, newPrice: 550 },
    { id: 24, category: "Салаты", name: "Салат со стручковой фасолью", oldPrice: 550, newPrice: 600 },
    { id: 25, category: "Салаты", name: "Цезарь с креветками", oldPrice: 550, newPrice: 600 },
    { id: 26, category: "Салаты", name: "Цезарь с курицей", oldPrice: 500, newPrice: 550 },
    { id: 27, category: "Салаты", name: "Цезарь с сёмгой", oldPrice: 700, newPrice: 750 },
    { id: 28, category: "Салаты", name: "Тбилисо", oldPrice: 550, newPrice: 600 },
    { id: 29, category: "Салаты", name: "Эгоист", oldPrice: 650, newPrice: 700 },
    { id: 30, category: "Салаты", name: "Хрустящие баклажаны", oldPrice: 550, newPrice: 600 },
    { id: 31, category: "Салаты", name: "Лобио с орехами", oldPrice: 300, newPrice: 350 },
    { id: 32, category: "Салаты", name: "Салат кучмачи", oldPrice: 500, newPrice: 550 },
    { id: 33, category: "Салаты", name: "Киноа с курицей", oldPrice: 450, newPrice: 500 },
    { id: 34, category: "Салаты", name: "Грузинский прованс", oldPrice: 600, newPrice: 650 },
    { id: 35, category: "Салаты", name: "По-домашнему", oldPrice: 300, newPrice: 350 },
    { id: 36, category: "Салаты", name: "По-домашнему грузинский", oldPrice: 550, newPrice: 600 },
    // Мучное
    { id: 37, category: "Мучное", name: "Хинкали с говядиной", oldPrice: 550, newPrice: 600 },
    { id: 38, category: "Мучное", name: "Хинкали с сыром", oldPrice: 500, newPrice: 550 },
    { id: 39, category: "Мучное", name: "Хинкали жареные", oldPrice: 600, newPrice: 650 },
    { id: 40, category: "Мучное", name: "Хачапури по-аджарски", oldPrice: 550, newPrice: 600 },
    { id: 41, category: "Мучное", name: "Хачапури по-имеретински", oldPrice: 600, newPrice: 650 },
    { id: 42, category: "Мучное", name: "Хачапури по-мегрельски", oldPrice: 650, newPrice: 700 },
    { id: 43, category: "Мучное", name: "Лобиани", oldPrice: 400, newPrice: 450 },
    { id: 44, category: "Мучное", name: "Мчади", oldPrice: 200, newPrice: 250 },
    { id: 45, category: "Мучное", name: "Чвиштари", oldPrice: 500, newPrice: 550 },
    // Супы
    { id: 46, category: "Супы", name: "Харчо", oldPrice: 450, newPrice: 500 },
    { id: 47, category: "Супы", name: "Уха", oldPrice: 500, newPrice: 550 },
    { id: 48, category: "Супы", name: "Чанахи", oldPrice: 450, newPrice: 500 },
    { id: 49, category: "Супы", name: "Куриный", oldPrice: 400, newPrice: 450 },
    { id: 50, category: "Супы", name: "Татариахни", oldPrice: 400, newPrice: 450 },
    { id: 51, category: "Супы", name: "Чечевичный крем-суп", oldPrice: 400, newPrice: 450 },
    { id: 52, category: "Супы", name: "Грибной крем-суп", oldPrice: 400, newPrice: 450 },
    // Пицца
    { id: 53, category: "Пицца", name: "Пицца Мясная", oldPrice: 650, newPrice: 700 },
    { id: 54, category: "Пицца", name: "Пицца Пепперони", oldPrice: 650, newPrice: 700 },
    { id: 55, category: "Пицца", name: "Пицца Куриная", oldPrice: 650, newPrice: 700 },
    { id: 56, category: "Пицца", name: "Пицца Ассорти", oldPrice: 650, newPrice: 700 },
    { id: 57, category: "Пицца", name: "Пицца Маргарита", oldPrice: 650, newPrice: 700 },
    // Соусы
    { id: 58, category: "Соусы", name: "Сацебели", oldPrice: 100, newPrice: 130 },
    { id: 59, category: "Соусы", name: "Соус белый", oldPrice: 100, newPrice: 100 },
    { id: 60, category: "Соусы", name: "Ткемали", oldPrice: 100, newPrice: 100 },
    { id: 61, category: "Соусы", name: "Итальянский", oldPrice: 100, newPrice: 100 },
    { id: 62, category: "Соусы", name: "Сметана с чесноком", oldPrice: 50, newPrice: 100 },
    { id: 63, category: "Соусы", name: "Наршараб", oldPrice: 85, newPrice: 100 },
    { id: 64, category: "Соусы", name: "Мацони с мятой", oldPrice: 70, newPrice: 130 },
    // Закуски
    { id: 65, category: "Закуски", name: "Сырная тарелка", oldPrice: 500, newPrice: 550 },
    { id: 66, category: "Закуски", name: "Овощная нарезка", oldPrice: 500, newPrice: 550 },
    { id: 67, category: "Закуски", name: "Сациви", oldPrice: 400, newPrice: 450 },
    { id: 68, category: "Закуски", name: "Ассорти Пхали", oldPrice: 450, newPrice: 500 },
    { id: 69, category: "Закуски", name: "Баклажаны с орехами", oldPrice: 300, newPrice: 350 },
    { id: 70, category: "Закуски", name: "Хрустящий хлеб", oldPrice: 300, newPrice: 350 },
];
